### ISSUE TITLE
ArgumentError: Package Plots not found in current path.

### ISSUE THREAD

**Issue by dwaardenburg** [kpobrien/JosephsonCircuits.jl#1]
Very nice to finally speak to you Mr. O'Brien.
I have been meaning to instroduce myself for a while already but thus far the oppertunity did not present itself yet.
Really excited about using this package to simulate amplifiers with more realistic and/or complex ciruits.
The issue itself is rather small, basically I was missing the Plots package during installation.

**Information**
JosephsonCircuits version: v0.1.4
Julia version: 1.8.4
Operating system: Windows

**What is the current behavior?**
When installing the JosephsonCircuits on a new computer the examples do not run because they are missing the Plots package.

**Steps to reproduce the problem**
Try running the example scripts on a fresh computer.

**What is the expected behavior?**
The system needs to be able to find the Plots package and run the example code from this repository.

**Suggested solutions**
Add Pkg.add("Plots") to the setup instructions.

**Comment by kpobrien** [comment]
Thank you Daan, good to meet you also! I revised the README to include installing Plots.jl to run the examples. Don't hesitate to post if notice any other issues. The package should currently be able to simulate gain and quantum efficiency for arbitrary circuits driven by a single microwave current source. In other words, four wave mixing processes. There is also crude code for cross-validating the gain with the more time consuming WRSPICE time domain simulations. Simulating three wave mixing, multiple pumps, and DC biases with JosephsonCircuits.jl are next on my list.

**Comment by dwaardenburg** [comment]
Thank you for the quick response, indeed already seeing many updates to the codebase. So far it is just playing with values for me, the previous simulations I was able to get running did not really allow me to look into changing the model very drastically (fabrication errors and linear transmission line segments).

I do have two more questions though, one is a feature request in terms of coupling more elements to the amplifier circuit. Would you prefer I make a separate issue for that? Otherwise I could just elaborate in this one.

Secondly, with amplifiers being a non-linear medium it can be quite hard to find (external) discussion partners besides my colleagues. It would be interesting for me to be able to ask some physics/circuit related questions, is there maybe someone from your group that would occasionally have the time for a more in depth discussion?

**Comment by kpobrien** [comment]
Regarding coupling more elements to the amplifier circuits, yes, please do make a new issue just to keep things organized in case other people run into the same issues. I'll mark this issue as closed by commit 28142f1702196bc35e91cec8a5b9857c720a91a0 . 

Re nonlinear device discussions, you're welcome to post relevant issues here or send me an email at the address listed on my group website.
